### ISSUE TITLE
i honestly dont know how will making custom drinks work so i can get an example thing here

### ISSUE THREAD

**Issue by bigchunges402960402** [Jsinco/BreweryX#10]
cause this plugin is a fork and i do not expect to be the same as the original version so i want to know if its possible to make custom drinks the normal way or do i have to use a different method?

**Comment by Jsinco** [comment]
BreweryX is basically the exact same as Brewery in terms of declaring recipes and creating potions/brews. Visit the original Brewery wiki or join the Discord for support from other members.

**Comment by bigchunges402960402** [comment]
thanks for that
