### ISSUE TITLE
Question about the plugin

### ISSUE THREAD

**Issue by d0ddn** [Jsinco/BreweryX#32]
What do you think about your rework and this plugin?

I have a dispute with my admin staff and they say that in terms of this plugin, everything except the standard config does not make sense, what do you think about this?

I think that there is no point in this plugin if players want to burp and just cook something for several real hours for the effect of a couple of minutes

**Comment by Jsinco** [comment]
I’m confused, what is the question?

**Comment by TomLewis** [comment]
Thats nice, then don't use it.

I think there is no point in this ticket and it should be closed.
