### ISSUE TITLE
Console Error For Redeeming Recipe

### ISSUE THREAD

**Issue by DemarcoFC** [Jsinco/BreweryX#6]
When attempting to right-click and redeem a recipe found in a chest, these messages show up in the console: https://pastebin.com/mmFF1cGb

And the recipe does not show up in the recipe gui either. It just goes away. There also was no permission added to the player via luckperms.

**Comment by Jsinco** [comment]
This should have been reported on [the RecipesAddon Github](https://github.com/Jsinco/BreweryRecipesAddon), but nonetheless, has been fixed in 1.10-BETA.
